include: package:very_good_analysis/analysis_options.yaml
analyzer:
  exclude:

formatter:  
  page_width: 120

linter:
  rules:
    one_member_abstracts: false
    prefer_relative_imports: true
    always_use_package_imports: false
    always_specify_types: true
    omit_local_variable_types: false
    public_member_api_docs: false
    lines_longer_than_80_chars: false